spring.application.name=ecommerce
# import properties
spring.config.import=application_local.properties


frontend.URL=${FRONTEND_URL}

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.password=

# PostgreSQL
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

spring.security.user.name=${DEV_USERNAME}
spring.security.user.password=${DEV_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#jwt
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtCookieName=${JWT_COOKIE_NAME}
jwt.refreshtokenExpirationMs=${REFRESH_EXPIRATION_MS}
spring.app.jwtRefreshCookieName=${JWT_REFRESH_COOKIE_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# AWS setting
aws.s3.region=${AWS_REGION}
aws.endpoint.url=${AWS_ENDPOINT}
aws.s3.bucket.name=${AWS_BUCKETNAME}
aws.access.key.id=${ACCESS_KEY}
aws.secret.access.key=${SECRET_ACCESS_KEY}

#Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}

#logs
msg.address.service001="Address has been deleted. Address ID:"
msg.cart.service002="The product is out of stock."
msg.cart.service003="Available quantity in stock:"
msg.cart.service004="Cart item with the given product ID and cart ID was not found"
msg.cart.service005="The cart is empty."
msg.cart.service006="Product was removed from the cart. Product name:"
msg.category.service001="No category is present."
msg.product.service001="No products found."
msg.product.service002="The product name is already used."
msg.product.service003="No featured products present"

