spring.application.name=ecommerce
# import properties
spring.config.import=application_prod.properties


frontend.URL=${FRONTEND_URL}

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.password=

# PostgreSQL
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

spring.security.user.name=${DEV_USERNAME}
spring.security.user.password=${DEV_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#jwt
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtCookieName=${JWT_COOKIE_NAME}
jwt.refreshtokenExpirationMs=${REFRESH_EXPIRATION_MS}
spring.app.jwtRefreshCookieName=${JWT_REFRESH_COOKIE_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# AWS setting
aws.s3.region=${AWS_REGION}
aws.endpoint.url=${AWS_ENDPOINT}
aws.s3.bucket.name=${AWS_BUCKETNAME}
aws.access.key.id=${ACCESS_KEY}
aws.secret.access.key=${SECRET_ACCESS_KEY}
aws.s3.storage.class=${STORAGE_CLASS}

#Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}

#logs
msg.address.service001="Address has been deleted. Address ID:"
msg.cart.service001="The product is out of stock."
msg.cart.service002="Available quantity in stock: "
msg.cart.service003="Cart item with the given product ID and cart ID was not found"
msg.cart.service004="The cart is empty."
msg.cart.service005="Product was removed from the cart. Product name: "
msg.category.service001="No category is present."
msg.product.service001="No products found."
msg.product.service002="The product name is already used."
msg.product.service003="No featured products present"
msg.userdetails.service001="User is not found. Username: "
authtokenfilter.msg001="Auth Token filter will be applied. URI: {}"
authtokenfilter.msg002="AuthTokenFilter.java: {}"
authtokenfilter.msg003="JWT is empty."
authtokenfilter.msg004="User roles : {}"
auth.entry.point.msg001="Authentication Error: {}"
jwt.utils.msg001="Invalid JWT: {}"
jwt.utils.msg002="JWT is not supported: {}"
jwt.utils.msg003="Invalid JWT claims: {}"
auth.util.msg001="User is not found. Username: "
auth.controller.msg001="Refresh Token has expired."
auth.controller.msg002="JWT has been regenerated."
auth.controller.msg003="Refresh Token is empty."
auth.controller.msg004="Username is already in use."
auth.controller.msg005="Email is already in use."
auth.controller.msg006="Role is not found."
auth.controller.msg007="Your account has been created."
auth.controller.msg008="You've been logged out."

#jwt.utils.msg001="JWTトークンが不正: {}"
#jwt.utils.msg002="JWTトークンがサポートされていません。: {}"
#jwt.utils.msg003="JWTのclaimsの値が不正です。: {}"
#auth.util.msg001=ユーザデータが存在しません。ユーザ名：

